---
vrs_config: /etc/default/openvswitch
vsp_k8s_dir: /usr/share/vsp-k8s
vsp_k8s_yaml: "{{ vsp_k8s_dir }}/vsp-k8s.yaml"
client_cert: "{{ vsp_k8s_dir }}/nuage.crt"
client_key: "{{ vsp_k8s_dir }}/nuage.key"
ca_cert: "{{ vsp_k8s_dir }}/ca.crt"
api_server: "{{ openshift_node_master_api_url }}"
docker_bridge: "docker0"
